#!/bin/sh
##Using standard queue
#PBS -q stdq1
##Request 1 nodes, 1 cores on each node
#PBS -l select=1:ncpus=1:mem=150gb
##Job will be terminated after walltime
#PBS -l walltime=240:00:00
##Give the job a name
#PBS -N calculate_Loglike
##Standard output folder
#PBS -o /home/Dong/Higher_model_mainland/higher_010/calculate_Loglike.OU
##Error output folder
#PBS -e /home/Dong/Higher_model_mainland/higher_010/calculate_Loglike.ER
##Verbose output
#PBS -V
module load r/4.0.5
Rscript /home/Dong/Higher_model_mainland/higher_010/calculate_Loglike.R