#!/bin/sh
##Using standard queue
#PBS -q stdq1
##Request 1 nodes, 4 cores on each node
#PBS -l select=1:ncpus=4:mem=150gb
##Job will be terminated after walltime
#PBS -l walltime=240:00:00
##Give the job a name
#PBS -N HIgh35
##Standard output folder
#PBS -o /home/Dong/Higher_model_mainland/higher_010/HIgh35.OU
##Error output folder
#PBS -e /home/Dong/Higher_model_mainland/higher_010/HIgh35.ER
##Verbose output
#PBS -V 
module load r/4.0.5
Rscript /home/Dong/Higher_model_mainland/higher_010/Higer_order_model_103.R